cursor #eadfe6
cursor_text_color #d0c3cc

foreground            #eadfe6
background            #171217
selection_foreground  #3b2b3c
selection_background  #d7bfd5
url_color             #ebb5ed

# black
color0   #171217
color8   #4d444c

# red
color1   #ff8678
color9   #ffb4ab

# green
color2   #f19080
color10   #f6b8ae

# yellow
color3   #ffa3fd
color11   #ffd6fe

# blue
color4   #ff8678
color12   #ffb4ab

# magenta
color5   #f19080
color13   #f6b8ae

# cyan
color6   #ffa3fd
color14   #ffd6fe

# white
color7   #d0c3cc
color15   #eadfe6
